name: tests

on:
  push:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  schedule:
    - cron: '0 0 * * *'

jobs:
  doc-tests:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: xdebug
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Execute tests via PEST(PHPUnit)
        env:
          TORCHLIGHT_TOKEN: ${{ secrets.TORCHLIGHT_TOKEN }}
        run: ./vendor/bin/pest
